package time.no.see.mapper;

import java.util.List;

import time.no.see.model.beans.Sys_Resource;

public interface Sys_ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    int insert(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    int insertSelective(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    Sys_Resource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    int updateByPrimaryKeySelective(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    int updateByPrimaryKey(Sys_Resource record);

	List<Sys_Resource> selectByParentId(Long long1);
}