package time.no.see.model.beans;

import java.util.List;

public class Sys_Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.url
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_ids
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.permission
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.checked
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.path
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.available
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    private Boolean available;
    
    
    private List<Sys_Resource> children;
    
    
    public List<Sys_Resource> getChildren() {
		return children;
	}

	public void setChildren(List<Sys_Resource> children) {
		this.children = children;
	}

	
	@Override
	public String toString() {
		return "Sys_Resource [id=" + id + ", name=" + name + ", type=" + type + ", url=" + url + ", parentId="
				+ parentId + ", parentIds=" + parentIds + ", permission=" + permission + ", checked=" + checked
				+ ", path=" + path + ", available=" + available + ", children=" + children + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_ids
     *
     * @return the value of sys_resource.parent_ids
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_ids
     *
     * @param parentIds the value for sys_resource.parent_ids
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.permission
     *
     * @return the value of sys_resource.permission
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.permission
     *
     * @param permission the value for sys_resource.permission
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.checked
     *
     * @return the value of sys_resource.checked
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.checked
     *
     * @param checked the value for sys_resource.checked
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setChecked(String checked) {
        this.checked = checked == null ? null : checked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.path
     *
     * @return the value of sys_resource.path
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.path
     *
     * @param path the value for sys_resource.path
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.available
     *
     * @return the value of sys_resource.available
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.available
     *
     * @param available the value for sys_resource.available
     *
     * @mbggenerated Mon Jul 01 22:23:38 CST 2019
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}